services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    container_name: laravel_avaliacao_develop
    restart: unless-stopped
    ports:
      - "8001:80"  # Porta diferente para desenvolvimento
    volumes:
      # Em desenvolvimento, mantemos volumes para hot reload
      - .:/var/www/html
      - /var/www/html/node_modules
      - /var/www/html/vendor
    networks:
      - rede_avaliacao_develop
    environment:
      - APP_ENV=develop
      - APP_DEBUG=true
      - CONTAINER_ROLE=app
    env_file:
      - .env.develop
    depends_on:
      - redis
      - db

  # Banco de dados para desenvolvimento (opcional)
  db:
    image: mysql:8.0
    container_name: mysql_avaliacao_develop
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: avaliacao360_develop
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: sail
    volumes:
      - db_data_develop:/var/lib/mysql
    ports:
      - "3307:3306"  # Porta diferente para não conflitar
    networks:
      - rede_avaliacao_develop

  # Redis para cache e sessões
  redis:
    image: redis:7-alpine
    container_name: redis_avaliacao_develop
    restart: unless-stopped
    ports:
      - "6380:6379"  # Porta diferente para desenvolvimento
    networks:
      - rede_avaliacao_develop

  # Queue worker
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: queue_avaliacao_develop
    restart: unless-stopped
    command: php artisan queue:work --tries=3 --timeout=90
    volumes:
      - .:/var/www/html
    networks:
      - rede_avaliacao_develop
    environment:
      - APP_ENV=develop
      - CONTAINER_ROLE=queue
    env_file:
      - .env.develop
    depends_on:
      - app
      - redis

volumes:
  db_data_develop:
    driver: local

networks:
  rede_avaliacao_develop:
    driver: bridge